"""
Django settings for Products project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(env_file=str(BASE_DIR) + '/.env')
SECRET_KEY = os.environ.get('SECRET_KEY', "secret")
DEBUG = os.environ.get('DEBUG') == 'True'
#SECRET_KEY = env('SECRET_KEY')
#print("secret_key", SECRET_KEY)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['*']

AUTHENTICATION_BACKENDS = [
	'django.contrib.auth.backends.ModelBackend',
]

#AUTHENTICATION_BACKENDS = [
#	'userena.backends.UserenaAuthenticationBackend',
#	'guardian.backends.ObjectPermissionBackend',
#	'django.contrib.auth.backends.ModelBackend',
#]

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'rest_framework',
	'rest_framework_simplejwt',
	'corsheaders',
	'User',
	'Products',
]

CORS_ALLOWED_ORIGINS = [
	"http://localhost:5173",
	"http://localhost:3000",
	"http://localhost:3001",

]

CORS_ALLOW_METHODS = [
'DELETE',
'GET',
'OPTIONS',
'PATCH',
'POST',
'PUT',
]

CORS_ALLOW_HEADERS = [
'accept',
'accept-encoding',
'authorization',
'content-type',
'dnt',
'origin',
'user-agent',
'x-csrftoken',
'x-requested-with',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'User.middleware.JSONTranslationMiddleware',
]

ROOT_URLCONF = 'Products.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
				'context_processors': [
						'django.template.context_processors.debug',
						'django.template.context_processors.request',
						'django.contrib.auth.context_processors.auth',
						'django.contrib.messages.context_processors.messages',
				],
			},
	},
]

#WSGI_APPLICATION = 'Products.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
			'NAME': env("DATABASE_NAME"),
			'USER': env("DATABASE_USER"),
			'PASSWORD': env("DATABASE_PASSWORD"),
			'HOST': env("DATABASE_HOST"),
			'PORT': env("DATABASE_PORT"),
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
			'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
			'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
			'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
			'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000/']


#ALLOWED_HOSTS=['*']
#CORS_ORIGIN_ALLOW_ALL = True
